- id: generate-documentation
  name: Generate documentation
  description: "Generates documentation using Pydoc-Markdown"
  entry: python -m build_documentation
  language: python
  types_or: [python, pyi]
  args: ["-f"]
  pass_filenames: true
  additional_dependencies: []
